### ISSUE TITLE
Private Google Group mbox file not generated

### ISSUE THREAD

**Issue by bisherbas** [icy/google-group-crawler#20]
I set up everything correctly. Cookies, group name etc. And all thread and msg files have been downloaded successfully to their designated folders. However, mbox folder is empty. mbox has not been generated for some reason. Looking through the command window history, I do not see any error messages. Can you please help? Thanks. Running it on Ubuntu.

**Comment by icy** [comment]
Thank you @bisherbas for reporting. I'm sorry for any inconvenience: Google seems to block all raw messages of private groups. I don't even see any button to download original message when viewing any message in a group group. Do you see any?

The problem is really a challenge now and I have no idea to resolve it :(

**Comment by icy** [comment]
To confirm this: You can open the script generated by `crawler.sh`: There are a lot of links, for example

```
  __wget__ "./archlinuxvn-security//mbox/m.CQHXkpgxCxY.q_PjAm44zusJ" "https://groups.google.com/forum/message/raw?msg=archlinuxvn-security/CQHXkpgxCxY/q_PjAm44zusJ"
```

You can try to open the `raw` link on your browser if it works.

The interesting thing is that I have two different private groups. I can download messages from on of them (`archlinux-security`, as above), but I can't download any private message from the other. I will take some further look to understand the difference.

**Comment by bisherbas** [comment]
Closing since it's all working well now.
